var lang = {
    french: {
        systemname: [
            "Lysen",
            "Zelas",
            "Centra",
            "Vecis",
            "Ivurd",
            "Sentori",
            "Fasis",
            "Luya",
            "Kisae",
            "Gaia"
        ],
        etypes: [
            "Planète",
            "Lune",
            "Soleil",
            "Asteroide",
            "Trou Noir",
            "Vaisseau Alien",
            "Vaisseau Mère Alien",
            "Planète Alien",
        ],
        ttitles: [
            "Comment jouer ?",
            "Exploration",
            "Marché",
            "Technologies",
            "Galaxie",
            "Menu du jeu",
        ],
        ttexts: [
            "<h4>L'objecfif est d'obtenir des ressouces pour ensuite les revendre et ainsi obtenir de nouvelles technologies pour améliorer le rendement</h4><br><br>1. Vous pouvez commencer par lancer une mission d'exploration, pour ainsi gagner des ressources et des <i class='red sort amount up icon'></i>Points d'Exploration(EP)<br><br>2. Vendez vôtre marchandise et gagnez de l'argent !<br><br>3. Créez un drone dans les technologies pour automatiser l'obtention de ressources.<br><br>4. Si vous obtenez assez d'argent et que vous vous trouvez dans le système Gaia, vous pouvez changer de galaxie.",
            "L'exploration est l'objectif principal,<br> vous découvrirez de nouvelles destinations en gagnant des <i class='red sort amount up icon'></i> EP ainsi que des ressources.",
            "Le marché est l'endroit pour vendre vos marchandises et gagner de l'argent.<br> Les prix changent chaque jour et sur chaque système.<br><br>Il y a un code couleur pour indiquer la valeur de chaque ressource:<br>- <span class='rouge'>Très basse</span><br>- <span class='argent'>basse</span><br>- <span class=''>Normale</span><br>- <span class='vert'>Chère</span><br>- <span class='Gold'>Très chère</span>",
            "3 Technologies sont actuellement disponibles.<br>- Un drone qui donnera une certaine quantité de la ressource définie, cela dépend du niveau du drone.<br>- Un module d'Hyperespace qui peut débloquer de nouvelles destinations.<br>- Un module d'Hyperpropulsion qui peut réduire le coût de déplacement vers une autre destination.",
            "<h4>Le système de prestige du jeu</h4><br>En changeant de galaxie vous obtiendrez plus d'espaces pour l'inventaire.<br>Mais ceci augmentera aussi le nombre <i class='red sort amount up icon'></i> d'EP requis pour voyager.<br> Ce système permet aussi de réduire le temps de production du drone.",
            "Il y a aussi un menu qui peut vous servir à exporter/importer vôtre sauvegarde afin de pouvoir y rejouer sur un autre navigateur ou PC.",
        ],
        general: [
            "Type",
            "Description",
            "Coût",
            "Action",
            "Nom",
            "Valeur",
            "Inventaire",
            "Vente",
            "Niveau Actuel",
            "Accès",
            "Requis",
            "Niveau",
            "Hyperespace",
            "Hyperpropulsion",
            "Activé",
            "Désactivé",
        ],
        tabnames: [
            "Exploration",
            "Marché",
            "Hyperespace",
            "Drone",
            "Hyperpropulsion",
            "Galaxie",
        ],
        leftcol: [
            "Localisation",
            "Stats",
            "Inventaire",
        ],
        items: [
            "Thamium9",
            "Cuivre",
            "Cellule d'Énergie",
            "Zinc",
            "Nickel",
            "Fer",
            "Aluminium",
            "Iridium",
            "Or",
            "Platine",
            "Carbone",
            "Plutonium",
            "Heridium",
            "Emeril",
            "Titane",
            "Antimatière",
            "Radnox",
            "Omegon",
            "Rubeum",
            "Cymatygen"
        ],
        buttons: [
            "Entrer dans le Trou Noir",
            "Options & Statistiques",
            "Guide",
            "Contact",
            "Offrir un café ♥",
            "Menu",
            "Exploration",
            "Hangar",
            "Galaxie",
        ],
        exploration: [
            "Explorer",
            "Visiter",
            "Max",
        ],
        drones: [
            "Drone rouillé I",
            "Drone rouillé II",
            "Drone basique I",
            "Drone basique II",
            "Drone basique III",
            "Drone avancé I",
            "Drone avancé II",
            "Drone avancé III",
            "Drone alien I",
            "Drone alien II",
        ],
        combat: [
            "Bas",
            "Moyen",
            "Grave",
            "Critique",
            "ALERTE ! PIRATE DANS LA ZONE.",
            "Niveau de menace",
            "Niveau",
            "Pirate",
            "Vous",
            "Attaquer",
            "Se protéger",
            "Fuite",
        ],
    },
    english: {
        systemname: [
            "Lysen",
            "Zelas",
            "Centra",
            "Vecis",
            "Ivurd",
            "Sentori",
            "Fasis",
            "Luya",
            "Kisae",
            "Gaia"
        ],
        etypes: [
            "Planet",
            "Moon",
            "Sun",
            "Asteroid",
            "Black Hole",
            "Alien Spaceship",
            "Alien Flagship",
            "Alien Planet",
        ],
        ttitles: [
            "How to play ?",
            "Exploration",
            "Market",
            "Technologies",
            "Galaxy",
            "Game Menu",
        ],
        ttexts: [
            "<h4>The objective is to get ressouces then sell them to buy technologies to improve the render</h4><br><br>1. You can start with an exploration mission, you will gain ressources and <i class='red sort amount up icon'></i>Exploration Points(EP)<br><br>2. Sell your merchandises to the space market to gain money.<br><br>3. Create a Drone in the technologies to automate the collection of resources.<br><br>4. If your have the required amount of money and you are in Gaia, you can travel to another galaxy.",
            "The exploration is the main objective,<br> you will discover new locations by gaining <i class='red sort amount up icon'></i> EP and ressources.",
            "The market is the place to sell all your merchandises and get some money,<br> the prices are differents on every system & change every days.<br><br>There is a color code to indicate the values of every ressource:<br>- <span class='rouge'>Very Low</span><br>- <span class='argent'>Low</span><br>- <span class=''>Normal</span><br>- <span class='vert'>High</span><br>- <span class='Gold'>Expensive</span>",
            "3 Technologies are unlockables<br>- A drone that gives a certain amount of the defined item, depending of your current drone level.<br> - An hyperspace module that can unlock new locations.<br>- An hyperdrive module that can reduce the cost to travel to another location.",
            "<h4>The prestige system of the game</h4><br>The galaxy will give you more inventory places.<br>But it will also increase the <i class='red sort amount up icon'></i> EP needed to change your location.<br>This system also reduce the production time for the drone.",
            "There is also a menu where you can export/import or reset your savegame or re-open this guide.<br>Just click on Menu on the upper left corner of the screen.",
        ],
        general: [
            "Type",
            "Description",
            "Cost",
            "Action",
            "Name",
            "Value",
            "Inventory",
            "Sell",
            "Current level",
            "Access",
            "Require",
            "Level",
            "Hyperspace",
            "Hyperdrive",
            "Enabled",
            "Disabled",
        ],
        tabnames: [
            "Exploration",
            "Market",
            "Hyperspace",
            "Drone",
            "Hyperdrive",
            "Galaxy",
        ],
        leftcol: [
            "Location",
            "Stats",
            "Inventory",
        ],
        items: [
            "Thamium9",
            "Copper",
            "Power Cell",
            "Zinc",
            "Nickel",
            "Iron",
            "Aluminium",
            "Iridium",
            "Gold",
            "Platinum",
            "Carbon",
            "Plutonium",
            "Heridium",
            "Emeril",
            "Titanium",
            "Antimatter",
            "Radnox",
            "Omegon",
            "Rubeum",
            "Cymatygen"
        ],
        buttons: [
            "Enter in the Black Hole",
            "Options & Statistics",
            "Guide",
            "Contact",
            "Offer a coffee ♥",
            "Menu",
            "Exploration",
            "Hangar",
            "Galaxy",
        ],
        exploration: [
            "Explore",
            "Visit",
            "Max",
        ],
        drones: [
            "Rusty drone I",
            "Rusty drone II",
            "Basic drone I",
            "Basic drone II",
            "Basic drone III",
            "Advanced drone I",
            "Advanced drone II",
            "Advanced drone III",
            "Alien drone I",
            "Alien drone II",
        ],
        combat: [
            "Low",
            "Moderate",
            "Severe",
            "Critical",
            "ALERT ! PIRATE IN THE AREA.",
            "Threat level",
            "Level",
            "Pirate",
            "You",
            "Attack",
            "Take Cover",
            "Run Away",
        ],
    }
};
